// AUTO-GENERATED by scripts/syncAssets.ts — do not edit by hand.
export type AssetManifestEntry = { id: string; file: string; label: string };

export const generatedLogos: AssetManifestEntry[] = [
  {
    "id": "bolt",
    "file": "bolt.png",
    "label": "bolt"
  },
  {
    "id": "chatgpt",
    "file": "chatgpt.png",
    "label": "chatgpt"
  },
  {
    "id": "claude",
    "file": "claude.png",
    "label": "claude"
  },
  {
    "id": "claude-ai-symbol",
    "file": "Claude_AI_symbol.svg.webp",
    "label": "Claude AI symbol"
  },
  {
    "id": "claude-svg",
    "file": "claude-svg.svg",
    "label": "claude svg"
  },
  {
    "id": "cloudflare",
    "file": "Cloudflare.png",
    "label": "Cloudflare"
  },
  {
    "id": "discord",
    "file": "discord.png",
    "label": "discord"
  },
  {
    "id": "elevenlabs",
    "file": "elevenlabs.png",
    "label": "elevenlabs"
  },
  {
    "id": "figma",
    "file": "figma.png",
    "label": "figma"
  },
  {
    "id": "gemini",
    "file": "gemini.png",
    "label": "gemini"
  },
  {
    "id": "github",
    "file": "github.png",
    "label": "github"
  },
  {
    "id": "gmail",
    "file": "gmail.png",
    "label": "gmail"
  },
  {
    "id": "google-chrome",
    "file": "google-chrome.png",
    "label": "google chrome"
  },
  {
    "id": "grok",
    "file": "grok.png",
    "label": "grok"
  },
  {
    "id": "kilo-code",
    "file": "kilo-code.png",
    "label": "kilo code"
  },
  {
    "id": "lovable",
    "file": "lovable.png",
    "label": "lovable"
  },
  {
    "id": "midjourney",
    "file": "midjourney.png",
    "label": "midjourney"
  },
  {
    "id": "netlify",
    "file": "Netlify.png",
    "label": "Netlify"
  },
  {
    "id": "reddit",
    "file": "reddit.png",
    "label": "reddit"
  },
  {
    "id": "remotion",
    "file": "remotion.png",
    "label": "remotion"
  },
  {
    "id": "remotion",
    "file": "remotion.svg",
    "label": "remotion"
  },
  {
    "id": "stripe",
    "file": "stripe.png",
    "label": "stripe"
  },
  {
    "id": "supabase",
    "file": "supabase.png",
    "label": "supabase"
  },
  {
    "id": "vercel",
    "file": "Vercel.png",
    "label": "Vercel"
  },
  {
    "id": "vs-code",
    "file": "VS-Code.png",
    "label": "VS Code"
  },
  {
    "id": "x",
    "file": "x.png",
    "label": "x"
  }
];

export const generatedProps: AssetManifestEntry[] = [
  {
    "id": "broken-glass",
    "file": "broken-glass.png",
    "label": "broken glass"
  },
  {
    "id": "broom",
    "file": "broom.png",
    "label": "broom"
  },
  {
    "id": "browser-window",
    "file": "browser-window.png",
    "label": "browser window"
  },
  {
    "id": "bug",
    "file": "bug.png",
    "label": "bug"
  },
  {
    "id": "card-declined",
    "file": "card-declined.png",
    "label": "card declined"
  },
  {
    "id": "clock",
    "file": "clock.png",
    "label": "clock"
  },
  {
    "id": "coin",
    "file": "coin.png",
    "label": "coin"
  },
  {
    "id": "credit-card",
    "file": "credit-card.png",
    "label": "credit card"
  },
  {
    "id": "database",
    "file": "database.png",
    "label": "database"
  },
  {
    "id": "document",
    "file": "document.png",
    "label": "document"
  },
  {
    "id": "dollar-cupure",
    "file": "dollar-cupure.png",
    "label": "dollar cupure"
  },
  {
    "id": "envelope",
    "file": "envelope.png",
    "label": "envelope"
  },
  {
    "id": "eye",
    "file": "eye.png",
    "label": "eye"
  },
  {
    "id": "frustration",
    "file": "Frustration.png",
    "label": "Frustration"
  },
  {
    "id": "fuel-gauge",
    "file": "fuel-gauge.png",
    "label": "fuel gauge"
  },
  {
    "id": "idea",
    "file": "idea.png",
    "label": "idea"
  },
  {
    "id": "key",
    "file": "key.png",
    "label": "key"
  },
  {
    "id": "layer-stack",
    "file": "layer-stack.png",
    "label": "layer stack"
  },
  {
    "id": "link",
    "file": "link.png",
    "label": "link"
  },
  {
    "id": "padlock",
    "file": "padlock.png",
    "label": "padlock"
  },
  {
    "id": "paper-documents",
    "file": "paper-documents.png",
    "label": "paper documents"
  },
  {
    "id": "pen",
    "file": "pen.png",
    "label": "pen"
  },
  {
    "id": "pin",
    "file": "pin.png",
    "label": "pin"
  },
  {
    "id": "plane",
    "file": "plane.png",
    "label": "plane"
  },
  {
    "id": "pricetag",
    "file": "pricetag.png",
    "label": "pricetag"
  },
  {
    "id": "puzzle-joined",
    "file": "puzzle-joined.png",
    "label": "puzzle joined"
  },
  {
    "id": "puzzle-piece",
    "file": "puzzle-piece.png",
    "label": "puzzle piece"
  },
  {
    "id": "question",
    "file": "question.png",
    "label": "question"
  },
  {
    "id": "robot-helpers",
    "file": "robot-helpers.png",
    "label": "robot helpers"
  },
  {
    "id": "screen-panel",
    "file": "screen-panel.png",
    "label": "screen panel"
  },
  {
    "id": "shop",
    "file": "shop.png",
    "label": "shop"
  },
  {
    "id": "sync-arrows",
    "file": "sync-arrows.png",
    "label": "sync arrows"
  },
  {
    "id": "target",
    "file": "target.png",
    "label": "target"
  },
  {
    "id": "tower-leaning",
    "file": "tower-leaning.png",
    "label": "tower leaning"
  },
  {
    "id": "two-users",
    "file": "two-users.png",
    "label": "two users"
  },
  {
    "id": "user-avatar",
    "file": "user-avatar.png",
    "label": "user avatar"
  },
  {
    "id": "uturn",
    "file": "uturn.png",
    "label": "uturn"
  },
  {
    "id": "wallet",
    "file": "wallet.png",
    "label": "wallet"
  }
];

export const generatedSfx: AssetManifestEntry[] = [
  {
    "id": "bloom",
    "file": "bloom.wav",
    "label": "bloom"
  },
  {
    "id": "check",
    "file": "check.wav",
    "label": "check"
  },
  {
    "id": "counter",
    "file": "counter.wav",
    "label": "counter"
  },
  {
    "id": "counter-short",
    "file": "counter-short.wav",
    "label": "counter short"
  },
  {
    "id": "d-break",
    "file": "d-break.wav",
    "label": "d break"
  },
  {
    "id": "d-count",
    "file": "d-count.wav",
    "label": "d count"
  },
  {
    "id": "d-count-short",
    "file": "d-count-short.wav",
    "label": "d count short"
  },
  {
    "id": "d-done",
    "file": "d-done.wav",
    "label": "d done"
  },
  {
    "id": "d-enter",
    "file": "d-enter.wav",
    "label": "d enter"
  },
  {
    "id": "d-fix",
    "file": "d-fix.wav",
    "label": "d fix"
  },
  {
    "id": "d-mark",
    "file": "d-mark.wav",
    "label": "d mark"
  },
  {
    "id": "d-msg-in",
    "file": "d-msg-in.wav",
    "label": "d msg in"
  },
  {
    "id": "d-msg-out",
    "file": "d-msg-out.wav",
    "label": "d msg out"
  },
  {
    "id": "d-ping",
    "file": "d-ping.wav",
    "label": "d ping"
  },
  {
    "id": "d-pop",
    "file": "d-pop.wav",
    "label": "d pop"
  },
  {
    "id": "d-select",
    "file": "d-select.wav",
    "label": "d select"
  },
  {
    "id": "d-tick",
    "file": "d-tick.wav",
    "label": "d tick"
  },
  {
    "id": "d-word",
    "file": "d-word.wav",
    "label": "d word"
  },
  {
    "id": "drop",
    "file": "drop.wav",
    "label": "drop"
  },
  {
    "id": "msg-in",
    "file": "msg-in.wav",
    "label": "msg in"
  },
  {
    "id": "msg-out",
    "file": "msg-out.wav",
    "label": "msg out"
  },
  {
    "id": "paper-slide",
    "file": "paper-slide.mp3",
    "label": "paper slide"
  },
  {
    "id": "riser",
    "file": "riser.mp3",
    "label": "riser"
  },
  {
    "id": "riser-2",
    "file": "riser-2.wav",
    "label": "riser 2"
  },
  {
    "id": "select",
    "file": "select.wav",
    "label": "select"
  },
  {
    "id": "slam",
    "file": "slam.wav",
    "label": "slam"
  },
  {
    "id": "snap",
    "file": "snap.wav",
    "label": "snap"
  },
  {
    "id": "soft-whoosh",
    "file": "soft-whoosh.mp3",
    "label": "soft whoosh"
  },
  {
    "id": "splash",
    "file": "splash.wav",
    "label": "splash"
  },
  {
    "id": "swipe",
    "file": "swipe.wav",
    "label": "swipe"
  },
  {
    "id": "tick",
    "file": "tick.wav",
    "label": "tick"
  },
  {
    "id": "type",
    "file": "type.wav",
    "label": "type"
  },
  {
    "id": "type-word",
    "file": "type-word.mp3",
    "label": "type word"
  },
  {
    "id": "whoop-click",
    "file": "whoop-click.mp3",
    "label": "whoop click"
  },
  {
    "id": "whoosh",
    "file": "whoosh.wav",
    "label": "whoosh"
  }
];
