import { existsSync, mkdirSync, readdirSync, copyFileSync, writeFileSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { config } from "dotenv";

config({ path: path.resolve(process.cwd(), ".env.local") });

const ROOT = process.cwd();

/** Where the raw files live. Overridable so the art can sit outside the repo;
 * unset means the folders at the project root. */
export const SOURCE_DIRS = {
  logos: process.env.TIKMAKER_AI_PATH ?? path.join(ROOT, "ai"),
  props: process.env.TIKMAKER_PROPS_PATH ?? path.join(ROOT, "props"),
  sfx: process.env.TIKMAKER_SFX_PATH ?? path.join(ROOT, "sfx"),
  fonts: process.env.TIKMAKER_FONTS_PATH ?? path.join(ROOT, "fonts"),
};

const PUBLIC = path.join(ROOT, "public");
const LOGOS_OUT = path.join(PUBLIC, "assets", "logos");
const PROPS_OUT = path.join(PUBLIC, "assets", "props");
const SFX_OUT = path.join(PUBLIC, "assets", "sfx");
const FONTS_OUT = path.join(PUBLIC, "fonts");

const IMAGE_EXT = [".png", ".jpg", ".jpeg", ".webp", ".svg"];
const SFX_EXT = [".wav", ".mp3"];
const FONT_EXT = [".woff2", ".woff", ".otf", ".ttf"];

const MANIFEST_PATH = path.join(ROOT, "src", "registries", "assets.generated.ts");

function ensureDir(dir: string) {
  mkdirSync(dir, { recursive: true });
}

function toId(filename: string): string {
  return path
    .basename(filename, path.extname(filename))
    .toLowerCase()
    .replace(/[_\s]+/g, "-")
    .replace(/\.svg$/, "")
    .replace(/[^a-z0-9-]/g, "");
}

type ManifestEntry = { id: string; file: string; label: string };

function syncDir(srcDir: string, outDir: string, extensions: string[]): ManifestEntry[] {
  if (!existsSync(srcDir)) {
    console.warn(`[assets:sync] source missing, skipping: ${srcDir}`);
    return [];
  }
  ensureDir(outDir);

  const entries: ManifestEntry[] = [];
  for (const filename of readdirSync(srcDir)) {
    const ext = path.extname(filename).toLowerCase();
    if (!extensions.includes(ext)) continue;

    copyFileSync(path.join(srcDir, filename), path.join(outDir, filename));

    const id = toId(filename);
    const label = path
      .basename(filename, path.extname(filename))
      .replace(/[_-]+/g, " ")
      .replace(/\.svg$/, "")
      .trim();

    entries.push({ id, file: filename, label });
  }
  // `readdirSync` hands back the FILESYSTEM's order, which is not a defined
  // order at all: it varies by filesystem, by OS, and on APFS it shifts as
  // files are added and removed. The manifest is a committed source file, so
  // that turned every unrelated sync into a diff — the same entries, moved —
  // and left `assets.generated.ts` showing as modified with nothing to say.
  //
  // Sorting on `id` rather than `file` is what makes it stable across machines:
  // `toId` has already lowercased and stripped the name, so `Vercel.png` and
  // `vercel.png` land in the same place instead of wherever each platform's
  // case handling puts them. Compared by code point (never `localeCompare`,
  // which answers differently under a different locale — the one thing this is
  // trying to stop).
  return entries.sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : a.file < b.file ? -1 : a.file > b.file ? 1 : 0));
}

function syncFonts() {
  if (!existsSync(SOURCE_DIRS.fonts)) {
    console.warn(`[assets:sync] fonts source missing, skipping: ${SOURCE_DIRS.fonts}`);
    return;
  }
  ensureDir(FONTS_OUT);
  for (const filename of readdirSync(SOURCE_DIRS.fonts)) {
    const ext = path.extname(filename).toLowerCase();
    if (!FONT_EXT.includes(ext)) continue;
    copyFileSync(path.join(SOURCE_DIRS.fonts, filename), path.join(FONTS_OUT, filename));
  }
}

export type SyncResult = { logos: number; props: number; sfx: number; changed: boolean };

/**
 * Copies the raw asset folders into `public/` and regenerates
 * `assets.generated.ts`, which is what every registry reads (`propRegistry`,
 * `toolRegistry`, `sfxRegistry`) and therefore what the editor's Visuals and
 * Assets tabs list.
 *
 * Exported rather than run at import time so the dev server can call it too —
 * see `assetSyncPlugin` in `vite.config.ts`. A file dropped into `props/` is
 * otherwise invisible until someone remembers to run the CLI, which is exactly
 * the kind of hidden manual step that reads as "my asset didn't upload".
 */
export function syncAssets(): SyncResult {
  const logos = syncDir(SOURCE_DIRS.logos, LOGOS_OUT, IMAGE_EXT);
  const props = syncDir(SOURCE_DIRS.props, PROPS_OUT, IMAGE_EXT);
  const sfx = syncDir(SOURCE_DIRS.sfx, SFX_OUT, SFX_EXT);
  syncFonts();

  const manifestSource = `// AUTO-GENERATED by scripts/syncAssets.ts — do not edit by hand.
export type AssetManifestEntry = { id: string; file: string; label: string };

export const generatedLogos: AssetManifestEntry[] = ${JSON.stringify(logos, null, 2)};

export const generatedProps: AssetManifestEntry[] = ${JSON.stringify(props, null, 2)};

export const generatedSfx: AssetManifestEntry[] = ${JSON.stringify(sfx, null, 2)};
`;

  ensureDir(path.dirname(MANIFEST_PATH));
  // Only write when something actually changed: the manifest is a source file,
  // so rewriting it identical content still triggers an HMR round trip in the
  // editor for every unrelated file event the watcher sees.
  const previous = existsSync(MANIFEST_PATH) ? readFileSync(MANIFEST_PATH, "utf-8") : "";
  const changed = previous !== manifestSource;
  if (changed) writeFileSync(MANIFEST_PATH, manifestSource, "utf-8");

  return { logos: logos.length, props: props.length, sfx: sfx.length, changed };
}

// Running the file directly (`npm run assets:sync`) syncs once and reports.
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const result = syncAssets();
  console.log(
    `[assets:sync] synced ${result.logos} logos, ${result.props} props, ${result.sfx} sfx. Manifest ${result.changed ? "written" : "unchanged"}.`
  );
}
