import { existsSync, mkdirSync, readdirSync, copyFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { config } from "dotenv";

config({ path: path.resolve(process.cwd(), ".env.local") });

const ROOT = process.cwd();

const AI_PATH = process.env.TIKMAKER_AI_PATH ?? path.join(ROOT, "ai");
const PROPS_PATH = process.env.TIKMAKER_PROPS_PATH ?? path.join(ROOT, "props");
const SFX_PATH = process.env.TIKMAKER_SFX_PATH ?? path.join(ROOT, "sfx");
const FONTS_PATH = process.env.TIKMAKER_FONTS_PATH ?? path.join(ROOT, "fonts");

const PUBLIC = path.join(ROOT, "public");
const LOGOS_OUT = path.join(PUBLIC, "assets", "logos");
const PROPS_OUT = path.join(PUBLIC, "assets", "props");
const SFX_OUT = path.join(PUBLIC, "assets", "sfx");
const FONTS_OUT = path.join(PUBLIC, "fonts");

const IMAGE_EXT = [".png", ".jpg", ".jpeg", ".webp", ".svg"];
const SFX_EXT = [".wav", ".mp3"];
const FONT_EXT = [".woff2", ".woff", ".otf", ".ttf"];

function ensureDir(dir: string) {
  mkdirSync(dir, { recursive: true });
}

function toId(filename: string): string {
  return path
    .basename(filename, path.extname(filename))
    .toLowerCase()
    .replace(/[_\s]+/g, "-")
    .replace(/\.svg$/, "")
    .replace(/[^a-z0-9-]/g, "");
}

type ManifestEntry = { id: string; file: string; label: string };

function syncDir(srcDir: string, outDir: string, extensions: string[]): ManifestEntry[] {
  if (!existsSync(srcDir)) {
    console.warn(`[assets:sync] source missing, skipping: ${srcDir}`);
    return [];
  }
  ensureDir(outDir);

  const entries: ManifestEntry[] = [];
  for (const filename of readdirSync(srcDir)) {
    const ext = path.extname(filename).toLowerCase();
    if (!extensions.includes(ext)) continue;

    copyFileSync(path.join(srcDir, filename), path.join(outDir, filename));

    const id = toId(filename);
    const label = path
      .basename(filename, path.extname(filename))
      .replace(/[_-]+/g, " ")
      .replace(/\.svg$/, "")
      .trim();

    entries.push({ id, file: filename, label });
  }
  return entries;
}

function syncFonts() {
  if (!existsSync(FONTS_PATH)) {
    console.warn(`[assets:sync] fonts source missing, skipping: ${FONTS_PATH}`);
    return;
  }
  ensureDir(FONTS_OUT);
  for (const filename of readdirSync(FONTS_PATH)) {
    const ext = path.extname(filename).toLowerCase();
    if (!FONT_EXT.includes(ext)) continue;
    copyFileSync(path.join(FONTS_PATH, filename), path.join(FONTS_OUT, filename));
  }
}

const logos = syncDir(AI_PATH, LOGOS_OUT, IMAGE_EXT);
const props = syncDir(PROPS_PATH, PROPS_OUT, IMAGE_EXT);
const sfx = syncDir(SFX_PATH, SFX_OUT, SFX_EXT);
syncFonts();

const generatedDir = path.join(ROOT, "src", "registries");
ensureDir(generatedDir);

const manifestSource = `// AUTO-GENERATED by scripts/sync-assets.ts — do not edit by hand.
export type AssetManifestEntry = { id: string; file: string; label: string };

export const generatedLogos: AssetManifestEntry[] = ${JSON.stringify(logos, null, 2)};

export const generatedProps: AssetManifestEntry[] = ${JSON.stringify(props, null, 2)};

export const generatedSfx: AssetManifestEntry[] = ${JSON.stringify(sfx, null, 2)};
`;

writeFileSync(path.join(generatedDir, "assets.generated.ts"), manifestSource, "utf-8");

console.log(
  `[assets:sync] synced ${logos.length} logos, ${props.length} props, ${sfx.length} sfx. Manifest written.`
);
